name: Actualización del Servidor

on:
  push:
    branches:
      - main

jobs:
  update-server:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del Código
        uses: actions/checkout@v2

      - name: SSH y Git Pull en el Servidor
        run: |
          ssh usuario@server 'cd /home/lautaro/composes/apache/lautaro-landing && git pull'
