name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Connect to EC2 instance
        uses: appleboy/ssh-action@master
        with:
          host: 54.162.120.219
          username: admin
          key: ${{ secrets.EC2_WEB_PRIVATE_KEY }}

      - name: Git pull
        run: |
          cd /home/debian/sitio/lautaro-landing/
          sudo git pull
